//! Embeds the UI art (`assets/ui`) into the client binary.
//!
//! The texture kit (`assets/ui/ui_kit.json`, lane T) and the icon masters
//! (`assets/ui/icons/icons.json`, lane I) are read here and turned into two static tables of
//! `include_bytes!` entries in `$OUT_DIR/ui_assets.rs`. `uikit::assets` includes that file, so the
//! game runs from any working directory and from a packaged build with no asset folder, exactly
//! like the fonts. New textures or icons land by re-running the generators: the manifests are the
//! only list, and this script re-runs whenever anything under `assets/ui` changes.

use serde_json::Value;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let crate_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let ui = crate_dir.join("../../assets/ui");
    println!("cargo:rerun-if-changed={}", ui.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut out = String::from("// Generated by crates/gf_client/build.rs from assets/ui. Do not edit.\n\n");
    write_kit(&ui, &mut out);
    write_icons(&ui, &mut out);

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("ui_assets.rs");
    std::fs::write(&dest, out).expect("write ui_assets.rs");
}

fn read_json(path: &Path) -> Value {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

/// An absolute, forward-slashed path literal for `include_bytes!`.
fn lit(path: &Path) -> String {
    let p = path.to_string_lossy().replace('\\', "/");
    format!("{p:?}")
}

fn num(v: &Value) -> f64 {
    v.as_f64().unwrap_or(0.0)
}

fn write_kit(ui: &Path, out: &mut String) {
    let manifest = read_json(&ui.join("ui_kit.json"));
    let textures = manifest["textures"].as_array().expect("ui_kit.json: textures[]");
    out.push_str("/// Every texture of the UI kit (`assets/ui/ui_kit.json`), in manifest order.\n");
    out.push_str("pub static KIT: &[KitEntry] = &[\n");
    for t in textures {
        let file = t["file"].as_str().expect("texture.file");
        let path = ui.join(file);
        assert!(path.is_file(), "ui_kit.json lists a missing texture: {file}");
        let size = &t["size"];
        let logical = &t["logical_size"];
        let mode = match t["mode"].as_str().unwrap_or("stretch") {
            "nine_slice" => "NineSlice",
            "three_slice_h" => "ThreeSliceH",
            "fixed" => "Fixed",
            "tiled" => "Tiled",
            _ => "Stretch",
        };
        let s = &t["slice"];
        let slice = [num(&s["left"]), num(&s["top"]), num(&s["right"]), num(&s["bottom"])];
        // Dashed outlines tile their sides: one period per `tile_logical` logical px.
        let tile = if t["sides"].as_str() == Some("tile") { num(&t["tile_logical"]) } else { 0.0 };
        let _ = writeln!(
            out,
            "    KitEntry {{ path: {file:?}, bytes: include_bytes!({}), size: [{}, {}], logical: [{:.2}, {:.2}], \
             mode: KitMode::{mode}, slice: [{:.1}, {:.1}, {:.1}, {:.1}], side_tile: {tile:.2} }},",
            lit(&path),
            size[0].as_u64().unwrap_or(0),
            size[1].as_u64().unwrap_or(0),
            num(&logical[0]),
            num(&logical[1]),
            slice[0],
            slice[1],
            slice[2],
            slice[3],
        );
    }
    out.push_str("];\n\n");
}

fn write_icons(ui: &Path, out: &mut String) {
    let dir = ui.join("icons");
    let manifest = read_json(&dir.join("icons.json"));
    let icons = manifest["icons"].as_object().expect("icons.json: icons{}");
    let mut keys: Vec<&String> = icons.keys().collect();
    keys.sort();
    out.push_str("/// Every icon master (`assets/ui/icons/icons.json`): (key, category, PNG bytes), sorted by key.\n");
    out.push_str("pub static ICONS: &[(&str, &str, &[u8])] = &[\n");
    for key in keys {
        let entry = &icons[key.as_str()];
        let file = entry["file"].as_str().expect("icon.file");
        let path = dir.join(file);
        assert!(path.is_file(), "icons.json lists a missing icon: {file}");
        let category = entry["category"].as_str().unwrap_or("");
        let _ = writeln!(out, "    ({key:?}, {category:?}, include_bytes!({})),", lit(&path));
    }
    out.push_str("];\n");
}
